# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='regdate',
            new_name='reg_date',
        ),
    ]
